/**
 * react-viz-composer —— 声明式 SVG/Canvas 混合渲染引擎
 *
 * Umbrella：re-export @react-viz-composer/core + @react-viz-composer/kit
 *   - core → 引擎 + 形状
 *   - kit  → 半成品工具组件（Axis / Grid / Tooltip），样式由 props 控制
 *
 * 参考图表见 apps/charts（不发布）。
 */

export {
  default as ReactVizComposer,
  default,
  Rect,
  Ellipse,
  Line,
  Path,
  Text,
  Image,
  Points,
  LinearGradient,
  RadialGradient,
  ClipPath,
  Filter,
  Mask,
  Group,
  Animation,
  useViz,
  useVizFrame,
  useParentId,
  useSceneTree,
  VizEvent,
  Model,
  Graph,
  SceneTree,
  EventSystem,
  CanvasRenderer,
  SVGRenderer,
  Renderer,
} from '@react-viz-composer/core';

export type {
  AnimStep,
  AnimAttribute,
  AnimEasing,
  AnimTarget,
  AnimComputeContext,
  AnimationHandle,
  ViewportCullMargin,
  Viewport,
  RectData,
  EllipseData,
  LineData,
  PathData,
  TextData,
  ImageData,
  PointsData,
  GroupData,
  AnimationData,
  ElementData,
  ElementType,
  Transform,
  Point,
  EngineType,
  GradientStop,
  LinearGradientData,
  RadialGradientData,
  ClipPathData,
  FilterData,
  FilterEffect,
  MaskData,
  MaskMode,
  GraphOptions,
  ElementRecord,
  VizEventType,
  VizEventHandler,
  VizDragEvent,
  VizDragEventHandler,
  ShapeEventProps,
  SceneNode,
  SceneListener,
  SceneChangeReason,
  IVizContext,
  IVizFrameContext,
} from '@react-viz-composer/core';

export { Axis, Grid, Tooltip, Legend, MarkLine, MarkPoint, MarkArea, Crosshair, Brush } from '@react-viz-composer/kit';
export type {
  AxisProps,
  AxisScale,
  BandScaleLike,
  LinearScaleLike,
  GridProps,
  TooltipProps,
  LegendProps,
  LegendItem,
  MarkLineProps,
  MarkPointProps,
  MarkAreaProps,
  CrosshairProps,
  BrushProps,
} from '@react-viz-composer/kit';
